# Calcula digitos verificadores do cpf

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
cpfs = np.random.randint(0,10,(3,11))
cpfs

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7],
       [6, 8, 8, 1, 6, 7, 7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0, 3, 5, 0, 2, 3, 8]])

In [3]:
cpfs[:, 9] = np.zeros((3), dtype= int)   # zera 2 ultimos digitos
cpfs[:, 10] = np.zeros((3), dtype= int)
cpfs

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 0, 0],
       [6, 8, 8, 1, 6, 7, 7, 8, 1, 0, 0],
       [8, 9, 4, 3, 0, 3, 5, 0, 2, 0, 0]])

In [4]:
w1 = np.zeros(11, int)
w1[0:9] = np.arange(10, 1, -1)
w1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  0,  0])

In [5]:
# shapes: (a,b) * (b,c) = (a,c)     # dot: soma resultado
dv1 = np.dot(cpfs,w1) * 10 % 11 % 10
dv1

array([7, 2, 0], dtype=int32)

In [6]:
w2 = np.zeros(11, int)
w2[0:10] = np.arange(11, 1, -1)
w2

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  0])

In [7]:
dv2 = np.dot(cpfs,w2) * 10 % 11 % 10
dv2

array([3, 5, 0], dtype=int32)

In [8]:
cpfs[:, 9] = dv1
cpfs[:, 10] = dv2
cpfs

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 7, 3],
       [6, 8, 8, 1, 6, 7, 7, 8, 1, 2, 5],
       [8, 9, 4, 3, 0, 3, 5, 0, 2, 0, 0]])

In [9]:
l_cpf = cpfs.astype(str).tolist()
l_cpf

[['5', '0', '3', '3', '7', '9', '3', '5', '2', '7', '3'],
 ['6', '8', '8', '1', '6', '7', '7', '8', '1', '2', '5'],
 ['8', '9', '4', '3', '0', '3', '5', '0', '2', '0', '0']]

In [10]:
[''.join(d) for d in l_cpf]

['50337935273', '68816778125', '89430350200']

## partindo de uma lista

In [35]:
cpfs = ['503379352', '688167781', '894303502']

In [39]:
col = 0
cpf_d = np.array(cpfs[0][col])
for col in range(1,9):
    cpf_d = np.append(cpf_d, np.array(cpfs[0][col]))
cpf_d    

array(['5', '0', '3', '3', '7', '9', '3', '5', '2'], dtype='<U1')

In [40]:
for l in range(1, len(cpfs)):
    col = 0
    cpf = np.array(cpfs[l][col])
    for col in range(1,9):
        cpf = np.append(cpf, np.array(cpfs[l][col]))
    cpf_d = np.append(cpf_d, cpf)
cpf_d

array(['5', '0', '3', '3', '7', '9', '3', '5', '2', '6', '8', '8', '1',
       '6', '7', '7', '8', '1', '8', '9', '4', '3', '0', '3', '5', '0',
       '2'], dtype='<U1')

In [42]:
cpf_d.reshape(len(cpfs),9)

array([['5', '0', '3', '3', '7', '9', '3', '5', '2'],
       ['6', '8', '8', '1', '6', '7', '7', '8', '1'],
       ['8', '9', '4', '3', '0', '3', '5', '0', '2']], dtype='<U1')