In [1]:
import numpy as np
import pandas as pd

## np.digitize
<https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5>

In [2]:
x = np.array([0.5])

In [3]:
bins = np.array([0,1,2,3])

In [4]:
np.digitize(x, bins)

array([1], dtype=int64)

In [5]:
x = np.array([1])

In [8]:
np.digitize(x, bins, right=False) # aberto a direita

array([2], dtype=int64)

In [9]:
np.digitize(x, bins, right=True) # fechado a direita

array([1], dtype=int64)

In [10]:
x = np.array([1.7, 2.4])
np.digitize(x, bins)

array([2, 3], dtype=int64)

## np.repeat

In [11]:
np.repeat(1,3)

array([1, 1, 1])

## np.polyfit

In [19]:
df = pd.read_excel('plan_linear.xls')
df.head(3)

Funcionario  tempo  clientes
0        Beto      2        48
1       Nivia      3        50
2        Bina      4        56

In [20]:
np.polyfit(df.tempo, df.clientes, 1)

array([ 2.95180723, 39.6746988 ])

## np.polyval

In [21]:
fit = np.polyfit(df.tempo, df.clientes, 1)

In [24]:
np.polyval(fit, 4)

51.48192771084337

In [25]:
np.nan

nan