In [1]:
import numpy as np

In [4]:
i1D = np.array([1, 2, 3])
i1D.dtype

dtype('int32')

In [5]:
s1D = np.array([1, 2, 3], dtype = str)
s1D

array(['1', '2', '3'], dtype='<U1')

In [6]:
i2D = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
i2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((3, 4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
np.ones((4, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [13]:
np.arange(10, 20, 5)

array([10, 15])

In [20]:
np.linspace(0, 10, 5, dtype = int)   # 5 valores igualmente espaçados entre 0 e 10

array([ 0,  2,  5,  7, 10])

In [21]:
np.full(3, 0)

array([0, 0, 0])

In [23]:
np.full((2,3), 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
np.random.randint(0, 10, 5)   # 5 valores aleatórios entre 0 e 10

array([0, 7, 0, 1, 7])

In [26]:
np.random.randint(0, 10, (2,3))

array([[1, 3, 5],
       [4, 1, 3]])

In [29]:
np.random.random(3)         # 3 valores aleatórios entre 0 e 1

array([0.18717171, 0.00188391, 0.2171187 ])

In [30]:
np.random.random((2,3))

array([[0.08319443, 0.31054721, 0.24755456],
       [0.48710744, 0.11929077, 0.44314314]])

In [ ]:
a1D.size  # quantidade de elementos

In [ ]:
a2D.dtype  # tipo de elementos

In [ ]:
np.unique(ndarray)  # retorna valores únicos sem repetição

In [ ]:
a2D_3x8.flatten()  # linearizando - 1 dimensão

In [ ]:
a1D.reshape(4,6)  # para 2 dimensões: 4x6

In [ ]:
# Retorna array com elementos adicionados no final
np.append(a1D, [100, 130])

In [ ]:
np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical)
np.vstack((a2D, b2D))

In [ ]:
np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)

In [ ]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
np.hstack((b2D, c2D))

In [ ]:
np.hsplit(A,3)  # divisão horizontal